// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The verb:gh input (the check surface's `gh: {...}` map).
type GhInput struct {
	Op string `json:"op"`

	Repo string `json:"repo"`

	Pr int `json:"pr"`
}
